version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/LivekitApi"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/LivekitApi.Tests"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/LivekitApi.Example"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/LivekitRtc"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/LivekitRtc.Tests"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/LivekitRtc.Example"
    schedule:
      interval: "weekly"